### PR TITLE
Adding ability to torque on dynamixel pros at configuration time, if des...

### PR DESCRIPTION
**Pull request by jasedit**
...ired.

This needs testing on hardware.

### CODE REVIEW

**Comment by adzenith** [comment]
I checked out this branch, and I'm up-to-date with https://bitbucket.org/trec/valor_platforms/pull-request/105/fixes-launch-typo-and-allows-enabling/, but when I run René the dynamixels are not torqued on. Is there another step?

**Comment by jasedit** [comment]
This code was written blind, and probably needs debugging. I can try to get time on robot and test it out.

**Comment by adzenith** [comment]
Gotcha. I wasn't sure if I was just doing something wrong. Thanks!

**Comment by jasedit** [comment]
Updated with one character typo that was breaking things. Works now!

**Pull request merged**
